# ROS 2 topology parameters
nodes: 10

num_publishers:  # Dictionary mapping topic names to number of publishers
  laser_topic: 10
  image_topic: 13
  pcl_topic: 11
  speed_topic: 17
  vector_topic: 7
  byte_topic: 19

num_subscribers:  # Dictionary mapping topic names to number of subscribers
  laser_topic: 10
  image_topic: 13
  pcl_topic: 11
  speed_topic: 17
  vector_topic: 7
  byte_topic: 19

topics:  # List of topic names
  - laser_topic
  - image_topic
  - pcl_topic
  - speed_topic
  - vector_topic
  - byte_topic

msg_types:  # List of message types corresponding to topics
  - laser_scan
  - image
  - point_cloud2
  - twist
  - vector3
  - stamped8mb

publisher_configs:  # Publisher-specific configurations
  laser_topic:  # Configurations for laser_topic
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false
  image_topic:  # Configurations for image_topoc
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false
  pcl_topic:  # Configurations for pcl_topic
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false
  speed_topic:  # Configurations for speed_topic
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false
  vector_topic:  # Configurations for vector_topic
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false
  byte_topic:  # Configurations for byte_topic
    - freq_hz: 64  # Publishing frequency in hertz
      msg_pass_by: shared_ptr  # Message passing mechanism
      qos_depth: 10
      qos_history: keep_last
      qos_reliability: reliable
      qos_durability: volatile
      qos_deadline: default
      qos_lifespan: default
      qos_liveliness: system_default
      qos_liveliness_lease_duration: default
      qos_avoid_ros_namespace_conventions: false