# ROS 2 topology parameters

num_publishers:  # Dictionary mapping topic names to number of publishers
  laser_topic: 1

num_subscribers:  # Dictionary mapping topic names to number of subscribers
  laser_topic: 1

topics:  # List of topic names
  - laser_topic

msg_types:  # List of message types corresponding to topics
  - laser_scan


publisher_configs:  # Publisher-specific configurations
  laser_topic:  # Configurations for laser_topic
    - period_ms: 10  # Publishing period in milliseconds
      msg_pass_by: shared_ptr  # Message passing mechanism
